import Head from 'next/head';
import dynamic from 'next/dynamic';

import Nav from '@/components/nav';

const Search = dynamic(() => import('shop/Search').then((mod) => mod.Search), {
  ssr: true,
});

const Featured = dynamic(
  () => import('shop/Featured').then((mod) => mod.Featured),
  {
    ssr: true,
  },
);

export function Home({ featuredProps }) {
  return (
    <>
      <Head>
        <title>Next MF app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Search />
        <Nav />
        <Featured {...featuredProps} />
      </main>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const [featured] = await Promise.all([import('shop/Featured')]);

  if (featured.getServerSideProps) {
    const [featuredProps] = await Promise.all([
      featured.getServerSideProps(ctx),
    ]);
    return {
      props: {
        featuredProps: featuredProps.props,
      },
    };
  }

  return {
    props: {},
  };
};

export default Home;
